// const MONITOR_HEIGHT_IN = 12;
const PIX_PER_LINEAR_INCH = 50;
const IN_FROM_MONITOR = 18;
export const PX_BELOW_MONITOR_TOP = 200;
// export const MONITOR_HEIGHT_PX = MONITOR_HEIGHT_IN * PIX_PER_LINEAR_INCH;
export const PX_FROM_MONITOR = IN_FROM_MONITOR * PIX_PER_LINEAR_INCH;